name: Test

on: push

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          submodules: true

      - name: Setup python
        uses: actions/setup-python@v1

      - name: Build
        run: make

      - name: Upload application artifacts
        uses: actions/upload-artifact@v1
        with:
          name: apps-${{ matrix.os }}
          path: build/bin/

      - name: Upload module artifacts
        uses: actions/upload-artifact@v1
        with:
          name: modules-${{ matrix.os }}
          path: build/lib/